
[tasks."llm:generate_bundle"]
description = 'Generate LLM bundle output file using repomix'
hide = true # hide this task from the lis
run = """
#!/usr/bin/env bash
npx repomix --style xml --output-show-line-numbers --output output.txt --ignore **/uv.lock,**/package-lock.json,**/.env,content,assets,resources,static,functions,public,data,**/Cargo.lock,**/node_modules,**/target,**/dist,**/build,**/output.txt,**/yarn.lock,**/static/icons/
"""
