repos:
    # Pre-commit hooks for general file quality
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-json
          - id: check-toml
          - id: debug-statements
          - id: mixed-line-ending
            args: ["--fix=lf"]

    # Ruff - Modern Python linter and formatter
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.4
      hooks:
          # Run the linter
          - id: ruff # lint + auto-fix + format in one pass
            args: [--fix]
    # Python security linter
    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.7
      hooks:
          - id: bandit
            exclude: ^tests/

    # Type checking with mypy
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.11.2
      hooks:
          - id: mypy
            additional_dependencies: [types-requests, types-cachetools]
            args: [--ignore-missing-imports]

    # Dockerfile linting
    # - repo: https://github.com/hadolint/hadolint
    #   rev: v2.12.0
    #   hooks:
    #     - id: hadolint-docker
    #       files: Dockerfile*

    # YAML formatting
    # - repo: https://github.com/pre-commit/mirrors-prettier
    #   rev: v4.0.0-alpha.8
    #   hooks:
    #     - id: prettier
    #       files: \.(yaml|yml)$

# Configuration for specific hooks
ci:
    autofix_commit_msg: "style: auto fixes from pre-commit hooks"
    autofix_prs: true
    autoupdate_commit_msg: "chore: pre-commit autoupdate"
    autoupdate_schedule: weekly
