# ABOUTME: Development override for docker-compose with live reloading and debugging
# ABOUTME: Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: "3.8"

services:
  weather-app:
    build:
      context: .
      target: builder # Use builder stage for development
    volumes:
      - .:/app
      - /app/.venv # Exclude .venv from volume mount to preserve dependencies
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    command: ["uv", "run", "python", "main.py"]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - __pycache__/
            - "*.pyc"
            - .git/
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
