# ABOUTME: GitHub Actions workflow for running tests on every push and pull request
# ABOUTME: Tests across multiple Python versions with comprehensive coverage reporting

name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python 3.10
        run: uv python install 3.10

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run unit tests
        run: |
          uv run pytest tests/unit/ -v --cov=. --cov-report=xml --cov-report=term-missing

      - name: Run integration tests
        run: |
          uv run pytest tests/integration/ -v

      - name: Run frontend tests
        run: |
          uv run pytest tests/test_frontend.py -v

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-full:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python 3.10
        run: uv python install 3.10

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run complete test suite
        run: |
          uv run pytest tests/ -v --cov=. --cov-report=html --cov-report=xml --cov-report=term-missing --html=tests/report.html --self-contained-html

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-html
          path: tests/report.html

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-results
          path: htmlcov/

      - name: Check coverage threshold
        run: |
          uv run coverage report --fail-under=80
